# Generated by Django 4.2.1 on 2023-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(),
        ),
    ]
