# Generated by Django 4.2.1 on 2023-10-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промо-код', 'verbose_name_plural': 'Промо-коды'},
        ),
    ]
