# Generated by Django 4.2.1 on 2023-10-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_promocode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.promocode'),
        ),
    ]
