# Generated by Django 4.2.1 on 2023-08-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=300)),
                ('keywords', models.CharField(max_length=200)),
            ],
        ),
    ]
