# Generated by Django 4.2.1 on 2023-08-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoattributes',
            options={'verbose_name': 'SEO-атрибут', 'verbose_name_plural': 'SEO-атрибуты'},
        ),
        migrations.RenameField(
            model_name='seoattributes',
            old_name='keywords',
            new_name='alt_image',
        ),
    ]
