# Generated by Django 4.2.1 on 2023-08-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0004_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
