# Generated by Django 4.2.1 on 2023-08-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0005_sliderimage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=200, unique=True)),
                ('new_path', models.CharField(max_length=200)),
            ],
        ),
    ]
