# Generated by Django 4.2.1 on 2023-08-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0009_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
