# Generated by Django 4.2.1 on 2023-08-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0012_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
