# Generated by Django 4.2.1 on 2023-10-04 15:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0014_alter_seoattributes_alt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('section', models.IntegerField(choices=[(1, 'Компания'), (2, 'Клиентам')])),
            ],
            options={
                'verbose_name': 'Инфо-страница',
                'verbose_name_plural': 'Инфо-страницы',
            },
        ),
    ]
