# Generated by Django 4.2.1 on 2023-09-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_articles', to='blog.blogtag'),
        ),
    ]
