# Generated by Django 4.2.1 on 2023-09-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_views_counter_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/previews/'),
        ),
    ]
