# Generated by Django 4.2.1 on 2023-09-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preview',
        ),
    ]
