# Generated by Django 4.2.1 on 2023-08-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв о товарах', 'verbose_name_plural': 'Отзывы о товарах'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оценка товара', 'verbose_name_plural': 'Оценки товаров'},
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='comment',
            new_name='text_comment',
        ),
    ]
