# Generated by Django 4.2.1 on 2023-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_productreview_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='text_comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
