# Generated by Django 4.2.1 on 2023-08-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_delete_rating_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='user_name',
        ),
    ]
