# Generated by Django 4.2.1 on 2023-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_productreview_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
