# Generated by Django 4.2.1 on 2023-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_buyinoneclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket_history_table',
            field=models.TextField(blank=True),
        ),
    ]
