# Generated by Django 4.2.1 on 2023-08-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tech_comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
