# Generated by Django 4.2.1 on 2023-08-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_basket_history_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket_history_table',
        ),
    ]
