# Generated by Django 4.2.1 on 2023-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_deliverymethod_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
