# Generated by Django 4.2.1 on 2023-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_deliverymethod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
