# Generated by Django 4.2.1 on 2023-08-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_paymentmethod_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.deliverymethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.paymentmethod'),
        ),
    ]
