# Generated by Django 4.2.1 on 2023-09-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_rename_сity_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
