# Generated by Django 4.2.1 on 2023-10-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_promocode_user_promo_code'),
        ('orders', '0020_orderitem_price_at_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.promocode'),
        ),
    ]
