# Generated by Django 4.2.1 on 2024-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='form_fields',
            field=models.JSONField(default=dict),
        ),
    ]
