# Generated by Django 4.2.1 on 2023-07-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stripe_product_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='products_images/preview'),
        ),
    ]
