# Generated by Django 4.2.1 on 2023-07-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preview_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_images/'),
        ),
    ]
