# Generated by Django 4.2.1 on 2023-07-21 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
    ]
