# Generated by Django 4.2.1 on 2023-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(default='site_assets/product_image_plug.webp', upload_to='products_previews/'),
        ),
    ]
