# Generated by Django 4.2.1 on 2023-08-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_additionalproductimage_product_additional_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_images',
        ),
        migrations.DeleteModel(
            name='AdditionalProductImage',
        ),
    ]
