# Generated by Django 4.2.1 on 2023-08-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alternateproductimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlternateProductImage',
        ),
    ]
