# Generated by Django 4.2.1 on 2023-08-04 14:18

from django.db import migrations, models

import store.utils.additional_images_path_gen


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_delete_alternateproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.ImageField(blank=True, upload_to=store.utils.additional_images_path_gen.generate_additional_image_path),
        ),
    ]
