# Generated by Django 4.2.1 on 2023-08-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_additional_images_alterimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, default='products_previews/product_image_plug_preview.jpg', upload_to='products_previews/'),
        ),
    ]
