# Generated by Django 4.2.1 on 2023-08-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_redirect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Redirect',
        ),
    ]
