# Generated by Django 4.2.1 on 2023-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_delete_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_name',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='old_slug',
            field=models.SlugField(blank=True, editable=False, max_length=120),
        ),
    ]
