# Generated by Django 4.2.1 on 2023-08-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_product_old_name_product_old_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_name',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_slug',
            field=models.SlugField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
