# Generated by Django 4.2.1 on 2023-08-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0009_tag'),
        ('products', '0031_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='seo_manager.tag'),
        ),
    ]
