# Generated by Django 4.2.1 on 2023-08-31 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_product_total_price_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='site_assets/product_image_plug.jpg', upload_to='products_images/'),
        ),
        migrations.CreateModel(
            name='FeaturedSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='special_subcategories/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubcategory')),
            ],
            options={
                'verbose_name': 'Особая подкатегория',
                'verbose_name_plural': 'Особые подкатегории',
            },
        ),
    ]
