# Generated by Django 4.2.1 on 2023-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_product_image_featuredsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredsubcategory',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
