# Generated by Django 4.2.1 on 2023-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_featuredsubcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article_number',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
