# Generated by Django 4.2.1 on 2023-09-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_product_description_alter_product_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_price_id',
        ),
    ]
