# Generated by Django 4.2.1 on 2023-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='productcharacteristic',
            name='value',
            field=models.CharField(max_length=600),
        ),
    ]
