# Generated by Django 4.2.1 on 2023-09-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_alter_productcharacteristic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='value',
            field=models.CharField(max_length=800),
        ),
    ]
