# Generated by Django 4.2.1 on 2024-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_productsubcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='parent_category_slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
